---
- name: Get OSPF Status
  hosts: arista
  gather_facts: no

  tasks:
  - name: run multiple commands
    arista.eos.eos_command:
      commands:
      - show interfaces transceiver detail
      - show interfaces counters errors
      - show ip arp
      - show ip ospf neighbor 
      - show ip route
    register: result

  - name: view result 
    debug:
      msg: "{{ result.stdout_lines }}"
