---
- name: network configuration to git repos
  hosts: "3.121.78.6"
  gather_facts: no

  tasks:
    # fail with good error for Automation controller user
    - name: determine that both AAP and Machine credentials are set
      assert:
        that:
          - "lookup('env', 'CONTROLLER_USERNAME') !=''"
        fail_msg:
          - "This Job requires two credentials"
          - "Red Hat Ansible Automation Platform credential is not set"
          - "Please assign correct credentials to the Job Template"

    - name: determine that both AAP and Machine credentials are set
      debug:
        msg:
          - "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
          - "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
          - "{{ lookup('env', 'CONTROLLER_HOST') }}"

    - name: backup configuration
      include_role:
        name: "../roles/backup"
      when: ansible_network_os is defined

    - name: create time stamp for play
      set_fact:
        datetime: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"
      delegate_to: backup-server
      delegate_facts: true
      run_once: true

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /backup/
        state: directory
      delegate_to: backup-server
      become: true
      run_once: true

    - name: save configuration to backup server
      copy:
        src: "{{ config_output.backup_path }}"
        dest: "/backup/{{hostvars['backup-server'].datetime}}/"
      when: config_output is defined
      become: true
      delegate_to: backup-server

    - name: find backups
      find:
        paths: /backup
        file_type: directory
      register: backups
      run_once: true
      become: true
      delegate_to: backup-server
      delegate_facts: true
