---
- name: gather information from routers
  hosts: arista
  gather_facts: false
  vars:
    targethost: "192.168.0.1"
    
  tasks:
    - name: gather router facts
      arista.eos.eos_facts:

    - name: display version
      debug:
        msg: "{{ targethost }} : The IOS version is: {{ ansible_net_version }}"

    - name: display serial number
      debug:
        msg: "The serial number is:{{ ansible_net_serialnum }}"
