---
- name: gather information from routers
  hosts: arista
  gather_facts: false

  tasks:
    - name: gather router facts
      arista.eos.eos_facts:

    - name: display version
      debug:
        msg: "{{ ansible_eda.event }} : The IOS version is: {{ ansible_net_version }}"

    - name: display serial number
      debug:
        msg: "The serial number is:{{ ansible_net_serialnum }}"
